from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from cloud_study_api.main import app

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = REPOSITORY_ROOT / "contracts" / "api" / "openapi.json"
TYPESCRIPT_PATH = (
    REPOSITORY_ROOT / "apps" / "web" / "src" / "generated" / "api-schema.ts"
)


def render_openapi() -> str:
    return (
        json.dumps(app.openapi(), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )


def _typescript_type(schema: dict[str, Any]) -> str:
    schema_type = schema.get("type")
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        items = schema.get("items")
        return f"Array<{_typescript_type(items) if isinstance(items, dict) else 'unknown'}>"
    if schema_type == "object":
        return "Record<string, unknown>"
    return "string" if schema_type == "string" else "unknown"


def render_typescript(openapi_text: str) -> str:
    openapi = json.loads(openapi_text)
    health_schema = openapi["components"]["schemas"]["HealthResponse"]
    required = set(health_schema.get("required", []))
    lines = [
        "// This file is generated by tools/generate_contracts.py. Do not edit manually.",
        "",
        "export interface HealthResponse {",
    ]
    for name, schema in sorted(health_schema["properties"].items()):
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_typescript_type(schema)};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def _check_file(path: Path, expected: str) -> bool:
    if not path.is_file():
        print(
            f"missing generated contract: {path.relative_to(REPOSITORY_ROOT)}",
            file=sys.stderr,
        )
        return False
    if path.read_text(encoding="utf-8") != expected:
        print(
            f"generated contract drift: {path.relative_to(REPOSITORY_ROOT)}",
            file=sys.stderr,
        )
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API contract artifacts.")
    parser.add_argument(
        "--check", action="store_true", help="Fail when generated files drift."
    )
    args = parser.parse_args()

    openapi_text = render_openapi()
    typescript_text = render_typescript(openapi_text)
    if args.check:
        results = [
            _check_file(OPENAPI_PATH, openapi_text),
            _check_file(TYPESCRIPT_PATH, typescript_text),
        ]
        return 0 if all(results) else 1

    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPESCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(openapi_text, encoding="utf-8", newline="\n")
    TYPESCRIPT_PATH.write_text(typescript_text, encoding="utf-8", newline="\n")
    print("generated OpenAPI and TypeScript contracts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
